name: tangleGen_env
channels:
  - bioconda
  - r
  - http://statgen.org/wp-content/uploads/Softwares/pyplink
  - defaults
dependencies:
  - python=3.10
  - numpy=1.22.3
  - matplotlib=3.6.2
  - msprime=1.2.0
  - pandas=1.5.2
  - scikit-learn=1.0.2
  - scipy=1.8.1
  - networkx=3.0
  - bitarray=2.7.2
  - seaborn=0.12.2
  - pydot=1.4.2
  - setuptools=67.1.0
  - graphviz=2.50.0
  - pip=22.3.1
  - wheel=0.37.1
  - tqdm=4.64.1
  - ipython=8.10.0
  - demesdraw=0.4.0
  - pandas-plink=2.2.9
  - plink=1.90b6.21
  - stdpopsim=0.2.0
  - scikit-allel=1.3.6
  - bcftools=1.5
  - jupyter=1.0.0
  - conda-forge::ruff
